"""Alpha.3 Studio inspector order contract."""
from pathlib import Path
import sys, unittest
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'tools'))
from ui_schema import parse_ui

EXPECTED=[
    "input_mode",
    "exposure",
    "wb_mode",
    "wb_temp",
    "wb_duv",
    "wb_strength",
    "warm",
    "tint",
    "printer_r",
    "printer_g",
    "printer_b",
    "negative_on",
    "film_model",
    "neg_contrast",
    "neg_toe",
    "neg_shoulder",
    "neg_sat",
    "crosstalk",
    "adv_neg_density",
    "adv_neg_color",
    "adv_neg_sep",
    "adv_neg_shadow",
    "adv_neg_high",
    "adv_neg_warm",
    "adv_neg_green",
    "adv_neg_cool",
    "look_mode",
    "look_mix",
    "skin_protect",
    "skin_pick",
    "skin_pick_on",
    "skin_hue",
    "skin_width",
    "skin_sat_min",
    "skin_sat_max",
    "print_on",
    "print_contrast",
    "print_toe",
    "print_shoulder",
    "print_density",
    "print_sat",
    "adv_print_black",
    "adv_print_white",
    "adv_print_sep",
    "adv_print_warm",
    "adv_print_color",
    "optics_on",
    "optics_quality",
    "optics_mix",
    "optics_soft",
    "halation_amount",
    "halation_radius",
    "halation_threshold",
    "halation_tint",
    "bloom_amount",
    "bloom_radius",
    "bloom_threshold",
    "glow_amount",
    "glow_radius",
    "glow_threshold",
    "veil_amount",
    "veil_radius",
    "veil_threshold",
    "optics_view",
    "texture_on",
    "grain_gauge",
    "grain_amount",
    "grain_size",
    "grain_rough",
    "grain_color",
    "grain_shadow",
    "grain_mid",
    "grain_high",
    "grain_motion",
    "grain_seed",
    "lens_soft",
    "lens_radius",
    "micro_soft",
    "texture_view",
    "vignette_stops",
    "vignette_radius",
    "vignette_soft",
    "vignette_round",
    "vignette_x",
    "vignette_y",
    "diag_mode",
    "diag_tap",
    "inspect_stage",
    "reference_gray",
    "ev_span",
    "ev_step",
    "ev_low",
    "ev_high",
    "ev_soft",
    "range_pick",
    "range_pick_on",
    "range_hue",
    "range_width",
    "range_soft",
    "range_smin",
    "range_smax",
    "range_ymin",
    "range_ymax",
    "neutral_tol",
    "diag_gamut",
    "gamut_margin",
    "cal_profile",
    "cal_target",
    "cal_tol",
    "cal_neutral",
    "qc_margin",
    "qc_comp",
    "diag_gain",
    "diag_overlay",
    "split_pos",
    "diag_legend",
    "guide_mode",
    "guide_opacity",
    "output_gray",
    "gamut_on",
    "gamut_knee",
    "output_mode"
]

class StudioUILayoutTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.names=[c.name for c in parse_ui((ROOT/'src/YSEW_Film_Lab.dctl').read_text())]
    def test_exact_studio_order(self): self.assertEqual(self.names,EXPECTED)
    def test_input_first(self): self.assertEqual(self.names[0],'input_mode')
    def test_balance_anchor_label(self):
        ui={c.name:c for c in parse_ui((ROOT/'src/YSEW_Film_Lab.dctl').read_text())}
        self.assertEqual(ui['exposure'].label,'BAL Exposure')
    def test_output_last(self): self.assertEqual(self.names[-1],'output_mode')
    def test_output_block_last(self): self.assertEqual(self.names[-4:],['output_gray','gamut_on','gamut_knee','output_mode'])
    def test_workflow_anchors(self):
        anchors=['input_mode','exposure','negative_on','look_mode','print_on','optics_on','texture_on','vignette_stops','diag_mode','output_gray']
        pos=[self.names.index(x) for x in anchors]
        self.assertEqual(pos,sorted(pos))
if __name__=='__main__': unittest.main(verbosity=2)
